### ISSUE TITLE
Fatal Error, must be array

### ISSUE THREAD

**Issue by j2l** [mevdschee/php-crud-admin#2]
Hi,

It's been a long time I didn't touch php. Please bear with me :)
When I run `php build.php` or access it with browser I always get:
```
Fatal error: Uncaught TypeError: Argument 1 passed to Tqdev\PhpCrudAdmin\Column\DefinitionService::makeNamed() must be of the type array, null given, called in /var/www/html/admin.php on line 11372 and defined in /var/www/html/admin.php:11379 Stack trace: #0 /var/www/html/admin.php(11372): Tqdev\PhpCrudAdmin\Column\DefinitionService->makeNamed(NULL) #1 /var/www/html/admin.php(11338): Tqdev\PhpCrudAdmin\Column\DefinitionService->optimizeDatabase(Array) #2 /var/www/html/admin.php(12277): Tqdev\PhpCrudAdmin\Column\DefinitionService->__construct(Object(Tqdev\PhpCrudAdmin\Client\CrudApi)) #3 /var/www/html/admin.php(12429): Tqdev\PhpCrudAdmin\Admin->__construct(Object(Tqdev\PhpCrudAdmin\Config)) #4 {main} thrown in /var/www/html/admin.php on line 11379
```
While `php install.php` worked fine:
```
php install.php
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 8 installs, 0 updates, 0 removals
  - Downloading psr/http-message (1.0.1)
  - Downloading psr/http-server-handler (1.0.1)
  - Downloading psr/http-server-middleware (1.0.1)
  - Downloading psr/http-factory (1.0.1)
  - Downloading nyholm/psr7-server (0.3.0)
  - Downloading php-http/message-factory (v1.0.2)
  - Downloading nyholm/psr7 (1.2.1)
  - Downloading mevdschee/php-crud-api (v2.5.4)
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-server-handler (1.0.1): Extracting archive
  - Installing psr/http-server-middleware (1.0.1): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing nyholm/psr7-server (0.3.0): Extracting archive
  - Installing php-http/message-factory (v1.0.2): Extracting archive
  - Installing nyholm/psr7 (1.2.1): Extracting archive
  - Installing mevdschee/php-crud-api (v2.5.4): Extracting archive
Generating autoload files
6 files patched in 7 ms
```
I have
PHP 7.2.27 (cli) (built: Feb  1 2020 21:06:44) ( NTS )
running within a container (debian 10.2).
A MariaDB is running in another container.
Adminer container accesses it fine.

Any idea?
Thanks

**Comment by j2l** [comment]
After changing to 
         'driver' => 'mysql',
         'address' => '172.26.0.2',
            'username' => 'myusername',
            'password' => 'mypass',
            'database' => 'records',
            'controllers' => 'columns'
I get code 1000 but with the right database in the left column:
![cruadmin](https://user-images.githubusercontent.com/65325/82222738-fca71400-9921-11ea-9ae1-465f13a64fe5.png)

**Comment by j2l** [comment]
Ah, ok, the full URL should be: http://0.0.0.0/crudadmin.php/admin/table/list
BTW, I changed admin.php to crudadmin.php for my install.

**Comment by j2l** [comment]
Fine for me :)

Have a great day!

**Comment by mevdschee** [comment]
I'm glad you sorted this out. 

NB: "localhost" means  "use a unix socket" in the PDO driver.

**Comment by j2l** [comment]
> NB: "localhost" means "use a unix socket" in the PDO driver.

Ok, but how other php code solves it? 
They also use the same PDO driver and reach the MariaDB container at port 3306 (without being exposed BTW).

**Comment by mevdschee** [comment]
I think they use the address '127.0.0.1' instead of 'localhost' :-)

**Comment by j2l** [comment]
it didn't work with api.php, that's why I asked.

**Comment by mevdschee** [comment]
Hmm, I would love to help you but I can't reproduce the problem you see.

Please share the dockerfiles and docker compose file of your environment so that I can reproduce the problem you have connecting and help you solve it. Also share a link of a docker of another PDO based project that properly connects if you can (phpmyadmin maybe)?
