### ISSUE TITLE
Unsure why I keep getting this requested URL was not found on the server

### ISSUE THREAD

**Issue by vermontdevil** [mevdschee/php-crud-admin#3]
I have the parameters to connect the database set up correctly. I even tested it with the api.php file and it works fine.

But for the admin.php file, I keep getting that error?

my URL looks like this:

xxx.xxx.com/folder/admin.php/

Am I missing something?

Thanks

**Comment by mevdschee** [comment]
I'd love to help you, but a 404 is typically due to a server configuration problem, not a PHP code problem. Without any information on your environment I can't help you.

**Comment by vermontdevil** [comment]
Weird. the api and ui php files work great. No problems. But this one not so much. I looked at logs etc but nothing. Oh well - I was just curious to run this but not a must have. I'm content with the other two. Thanks!
